### ISSUE TITLE
Spring 2017 schedules

### ISSUE THREAD

**Issue by ritjoe** [FOSSRIT/fossbox-tasks#29] opened 2017-01-04 21:30 UTC
# Introduction

Let's open a conversation about what our schedules look like so far for the upcoming (Spring 2017) semester, in terms both of recurring weekly and monthly events (relevant classes, FOSS hours, meetups) and broader one-off events. 

We can open per-event issues if necessary to point back to or otherwise inform changes to this issue, but for now let's start with the bigger picture.

Some notable reference points of which @ritjoe is aware so far:

# Local and regional events
## Recurring events

**HFOSS class** Monday, Wednesday, Friday 9:00-9:50

**FOSS Culture class**

**FOSSTalks** These Wednesday afternoons, MAGIC Center: 2/15. 3/22, 4/19 4-6

**FOSS Hours** 4-6 non-FOSSTalk Wednesdays GOL-2500

[**RITLUG**](https://github.com/RITLUG) Every Friday, 4pm-6pm, GOL-2620

[**RocPy**](http://github.com/rocpy) [RocPy meetup page](https://www.meetup.com/Rochester-Python-Meetup)
Presentations on 3rd Tuesdays, Organization meeting on 4th Tuesdays.

**Linux Workshop** 3rd Saturdays.

[**codeRIT**](http://coderit.org) hack nights TBD

## One-off events

[TEDxAllendale Columbia](https://tedxallendalecolumbiaschool.org/) Feb 4, 2017.

[**BrickHack**](https://brickhack.io/) is February 11-12, 2017. [Brickhack page at Fedora events](https://fedoraproject.org/wiki/RIT_BrickHack/2017)

[**DandyHacks**](http://www.dandyhacks.org/) February 17-19, 2017.

[**WiCHacks**](http://wic-hacks.rit.edu/) February 25-26, 2017.

**Spring Break** is March 13-17, 2017.

[**FIRST Robotics**](https://www.rit.edu/gcr/firstrobotics/) March 15-18, 2017.

[**Hack Upstate IX**](http://hackupstate.com/) is April 8-9, 2017.

[NYCWIC](http://nycwic.hosting.acm.org/nycwic2017/program-2017/) April 21, 2017

**Space Apps Challenge** April 28-30?

[**Imagine RIT**](https://www.rit.edu/imagine/) May 6, 2017.

**Finals** are May 15-19, 2017.

# National and international events

[**GDC**](http://www.gdconf.com/) is February 27 through March 3, 2017.
[**SXSW**](https:/www.sxsw.com/) March 10-19, 2017
[**LibrePlanet**](https://libreplanet.org/2017/) March 25-26, 2017.
[**Red Hat Summit**](https://www.redhat.com/en/summit/2017/) May 2-5, 2017
[**OSCON**](http://conferences.oreilly.com/oscon/oscon-tx) May 8-11, 2017
[**PyCon**](https://us.pycon.org/2017/) May 17-25, 2017.

I'm going to mention people widely in hopes people can help fill any gaps in
what I've included so far, and to otherwise help people plan, particularly
those in the broader community who might not have as many opportunities to
get news of upcoming events. 

* @FOSSRIT/friends-of-foss 
* @FOSSRIT/foss-magic-faculty-and-staff 
* @FOSSRIT/students-class-of-2016 
* @FOSSRIT/students-class-of-2017 
* @FOSSRIT/students-class-of-2018 
* @FOSSRIT/students-class-of-2019 
* @FOSSRIT/students-class-of-2020
* @Interlock-Rochester

**Comment by itprofjacobs** [comment] 2017-01-04 22:06
Here’s what I know.


> On Jan 4, 2017, at 4:30 PM, Joe <notifications@github.com> wrote:
> 
> Introduction
> 
> Let's open a conversation about what our schedules look like so far for the upcoming (Spring 2017) semester, in terms both of recurring weekly and monthly events (relevant classes, FOSS hours, meetups) and broader one-off events.
> 
> We can open per-event issues if necessary to point back to or otherwise inform changes to this issue, but for now let's start with the bigger picture.
> 
> Some notable reference points of which @ritjoe <https://github.com/ritjoe> is aware so far:
> 
> Local and regional events
> 
> Recurring events
> 
> HFOSS class Monday, Wednesday, Friday 9:00-9:50
> 
> FOSS Culture class
> 
Dunno if it’s on
> FOSS Hours TBD?
> 
same as last time
> RITLUG <https://github.com/RITLUG> TBD?
> 
> RocPy <https://github.com/rocpy> RocPy meetup page <https://www.meetup.com/Rochester-Python-Meetup>
> Presentations on 3rd Tuesdays, Organization meeting on 4th Tuesdays.
> 
> 
FOSSTalks:
2/15. 3/22, 4/19 4-6
> Linux Workshop 3rd Saturdays.
> 
> codeRIT <http://coderit.org/> hack nights TBD
> 
> One-off events
> 
> BrickHack <https://brickhack.io/> is February 11-12, 2017. Brickhack page at Fedora events <https://fedoraproject.org/wiki/RIT_BrickHack/2017>Likely SJ and others judging FOSS projects as happened last year
> DandyHacks <http://www.dandyhacks.org/> February 17-19, 2017.
> 
> 
no FOSS@MAGIC support in the past.
> WiCHacks <http://wic-hacks.rit.edu/> February 25-26, 2017.
> 
We’ve offered support in the past. Sometimes with negative results though I believe that’s behind us.  Don’t know what Dan may have offered.
> Spring Break is March 13-17, 2017.
> 
> Hack Upstate IX <http://hackupstate.com/> is April 8-9, 2017.
> 
> 
Space Apps again (tentative) April 28-30

Imagine RIT March 6th
Should start discussing
> Finals are May 15-19, 2017.
> 
> National and international events
> 
> GDC <http://www.gdconf.com/> is February 27 through March 3, 2017.
> 
Notable only in that MAGIC will be a quiet place.  Little FOSS overlap
> SXSW <https://www.sxsw.com/> March 10-19, 2017
> 
No Participation on our end this year
> LibrePlanet <https://libreplanet.org/2017/> March 25-26, 2017.
> 
No Planned FOSS@MAGIC participation at this time.  Remy has gone in the past.

Red Hat Summit May 2-5.
Probable SJ and possible Dan attendance

OSCONC May 8th-11
Possible FOSS@MAGIC Table.  Pending. Would be funding for a few students to go.

> PyCon <https://us.pycon.org/2017/> May 17-25, 2017.
> 
No Participation from FOSS this year, Finals Week

**Comment by schneidy** [comment] 2017-01-04 22:58
Personal schedule for Spring:

Jan 20th-22nd - Maker Faire Producer's Summit in Miami
Feb 4th - Speaking at [TEDxAllendale Columbia](https://tedxallendalecolumbiaschool.org/)
March 15th - 18th - [FIRST Robotics Competition at RIT](https://www.rit.edu/gcr/firstrobotics/) (could use volunteers if any students are hanging around)
March 24th - NYS Maker Summit (TBA soon)
April 1st - [Fast Forward Film Festival](http://www.fastforwardroc.org/) (installing art at it)
April 21st - [NYCWIC](http://nycwic.hosting.acm.org/nycwic2017/program-2017/) - not involved, but something to be aware of.
May 19th - Speaking at [Science Exploration Days](http://www.ggw.org/~cws/sed.htm)

**Comment by cprofitt** [comment] 2017-01-05 00:45
My schedule for spring:
------------------------

Roobitcs Team Activities:
Monday, Thursday and Saturday from January 7th to February 18th (might
be more)

February 11th - 12th - Brick Hack
February 25th - 26th - WicHACKS (still need to ask organizer what I can
do to assist)
March 16th - 18th - FIRST Robotics Compeition (team 3181 mentor)

I am interested in HackUpstate and supporting RITLug, etc...

Charles

**Comment by jflory7** [comment] 2017-01-06 06:38
As far as **RITlug** goes, I haven't talked with @Serubin about it yet, but I think Fridays, 4pm-6pm will continue to be the meeting time. Not sure if Solomon wants to resume a weekly rate or keep it on even-numbered weeks like it was this semester.

Wednesday seems nice for FOSS Hours, perhaps if it's not too late, I could even video call in for a couple of them. 😃 But obviously since I'm not on campus, factoring in my schedule would be pointless.

This past semester, the codeRIT hack / workshop nights were every Friday, but I think @wilfriedE or @ColdSauce could speak a little more to whether it will remain the same this coming semester.

**Comment by ritjoe** [comment] 2017-01-10 18:27
OK, thanks for the comments. My omission in particular of Space Apps, FIRST, and most especially Imagine were pretty huge gaps you helped fill.  I've included in the lead post many if not most of the additional things mentioned.

Very useful to know what FOSS@MAGIC has on its plate for the semester, so thanks for those comments.

For my part, I like to let HFOSS students know what's going on eventwise. I try to be pretty inclusive in terms of what [events they can attend for meetup credit](https://people.rit.edu/djaigm/presentations/hfoss-meetups/preso).

A lot of [IGM](http://rit.edu/gccis/igm/) and a lot of IGM faculty and students, including HFOSS students, tend to go to GDC, so I wanted to have those dates on hand.

I'll continue to look forward to comments from @Serubin, @wilfriedE, and @ColdSauce about the events they're involved in.

**Comment by Serubin** [comment] 2017-01-10 20:46
FYI: Imagine is May 6th, not march.

**Comment by Serubin** [comment] 2017-01-10 20:49
@jflory7 @ritjoe: I'd like to keep RITLUG the same time unless there are any major objections. I also want to give a shot to every week, maybe doing presentations on even weeks only. I need to get room reservations for those nights set up.

I'm good on Fossbox on Wednesdays - I think that's what they were last year.

**Comment by cprofitt** [comment] 2017-01-11 01:35
Solomon:

I am available to do some presentations.

Charles

**Comment by ritjoe** [comment] 2017-01-24 17:53
@schneidy are your MAGIC Lab hours same this semester as last?

**Comment by schneidy** [comment] 2017-01-24 18:08
@ritjoe Sure. Might vary every now and then due to phone calls/meetings, but otherwise yes.

**Comment by ritjoe** [comment] 2017-01-24 23:59
:+1:

**Comment by ritjoe** [comment] 2017-02-03 01:53
An in-person comment from someone at FOSS Hours this week made me look again to see whether I'd fixed the Imagine RIT date yet or not.

When I look at the top post here __as edited__ it has it in May now, not March as I erroneously first had it.

See https://github.com/FOSSRIT/fossbox-tasks/issues/29#issue-198815777

**Comment by jflory7** [comment] 2017-02-03 11:40
Just a couple of notes:

@ritjoe, I edited your original comment to add in the current meeting time that @Serubin is following (which is the same as last semester, but weekly now, with talks on even weeks).

Also worth noting, there will very sadly not be a Fedora presence at BrickHack this year. 😞

**Comment by jflory7** [comment] 2017-02-03 11:42
Also another thought, what would qualify closing this issue, now that FOSS Hours are planned? Would it be better to get this info into some sort of static document in one of our repositories? I think _tracking_ this info is helpful, but I could also see how it could get lost and confusing this since the issue is more of like a discussion area.

**Comment by jflory7** [comment] 2017-02-25 22:33
Since it's been about a month, I'm going to go ahead and close this issue. It will be still be available should we need to refer back to it, but it would probably be a good idea to create a file or wiki page somewhere to archive this info.

Probably most related to #33…

**Closed by jflory7** 2017-02-25 22:33 UTC
Labels: internal, meetup, outreach
